### ISSUE TITLE
Ruby-devel & FPM - Missing Build Agent Software 

### ISSUE THREAD

**Issue by murphyj21** [plus3it/dotc-jenkins#14]
Ensure Ruby-devel and FPM are installed on Build Agents. 

`fpm --version` returned nada

ran
# Install FPM dependencies
`yum install ruby-devel gcc make rpm-build rubygems`

# install FPM
`gem install --no-ri --no-rdoc fpm`

`fpm --version`
1.9.2

**Comment by ferricoxide** [comment]
Weird: 
- `gcc`
- `make`
- `rpm-build`
- `rubygems` 

are all part of `@development`. Only `ruby-devel` is a separate package:

~~~
$ !rpm
rpm -qa ruby-devel gcc make rpm-build rubygems
rpm-build-4.11.3-21.el7.x86_64
rubygems-2.0.14.1-29.el7.noarch
make-3.82-23.el7.x86_64
gcc-4.8.5-11.el7.x86_64
~~~

**Comment by ferricoxide** [comment]
Looking a the manifest:

~~~
$ rpm -qa rubygems-devel fpm2
fpm2-0.79-12.el7.x86_64
rubygems-devel-2.0.14.1-29.el7.noarch
~~~

Don't have `ruby-devel` _do_ have `rubygems-devel`. Similarly, have `fpm2` (RPM), but not the `gem`-installed fpm. Will need clarification if these are sufficient or if need the `ruby-devel` RPM and the `gem`-installed fpm
