### ISSUE TITLE
Sonarqube Scanner - Missing Software on Build Agents

### ISSUE THREAD

**Issue by murphyj21** [plus3it/dotc-jenkins#17]
Sonarqube scanner needs to be installed on the build agents. 

for Jenkins --> https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins

Need clarification on this software install and use.

**Comment by ferricoxide** [comment]
Doesn't appear to be a deployment-automation issue: installs via dashboard. Closing (re-open if there's an actual deployment-automation to address).
