### ISSUE TITLE
Fix cron setup

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/dotc-jenkins#2]
The downloaded cron file uses `$(date "+%w")` in pathing for daily backups. Needs to be changed to `$(date "+\%w")`

**Comment by murphyj21** [comment]
I updated the time to reflect 1730 vice 0530 and added the \. Uploaded the file back to S3 in the devops-toolchain/SupportFiles directory.

**Comment by ferricoxide** [comment]
eventually we'll skip the use of a static source-file and shift to one generated at launch-time: use this issue as a place-holder till then.

**Comment by ferricoxide** [comment]
Issue has resolved for a while. Most recently, was re-addressed during the move from UserData to CFn-init.
